---
# tasks file for kubernetes

- name: Add the overlay module
  modprobe:
    name: overlay
    state: present

- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Letting iptables see bridged traffic, net.bridge.bridge-nf-call-iptables = 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
    state: present

- name: Letting iptables see bridged traffic, net.bridge.bridge-nf-call-ip6tables = 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
    state: present

- name: Letting iptables see bridged traffic, net.ipv4.ip_forward = 1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
    state: present

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_enp0s8.ipv4.address }} {{ hostvars[item].ansible_fqdn }} {{ hostvars[item].ansible_hostname }}"
    state: present
  with_items: "{{ groups.all }}"

- name: install packages
  apt: name={{ packages }} state=present autoremove=yes
  vars:
    packages:
      - chrony
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https

# - name: add apt key for docker packages
#   apt_key: url='https://download.docker.com/linux/ubuntu/gpg' state=present

# - name: add apt repository for docker
#   apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable' filename='docker' state=present update_cache=yes

# - name: install docker packages
#   apt: name={{ packages }} state=present autoremove=yes
#   vars:
#     packages:
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io

# - name: add vagrant user to docker group
#   user: name=vagrant groups=docker append=yes

# - name: Copy daemon.json to /etc/docker
#   copy: 
#     src: daemon.json
#     dest: /etc/docker/daemon.json
#     mode: 0644
#   notify:
#     - restart docker

# - name: Add vagrant user to docker group
#   user:
#     name: vagrant
#     group: docker

- name: Create directory /etc/containerd
  file:
    path: /etc/containerd
    state: directory
    mode: 755

- name: Copy config.toml to /etc/contrainerd
  copy: 
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: 0644

- name: install containerd packages
  apt:
    name: containerd
    state: present
    autoremove: yes

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet={{ k8s_packages_version }}
      - kubeadm={{ k8s_packages_version }}
      - kubectl={{ k8s_packages_version }}

- name: Prevent kubelet from being upgraded
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Prevent kubeadm from being upgraded
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Prevent kubectl from being upgraded
  dpkg_selections:
    name: kubectl
    selection: hold
