---
# This playbook deploys the whole application stack in this site.

- name: apply apt-cacher configuration
  hosts: all
  become: true

  roles:
  - apt-cacher

- name: apply common configuration to all nodes
  hosts: all
  become: True

  roles:
  - common
  - swapfile
