---
# tasks file for zabbix-hosts

- name: install zabbix package to configure remote repository
  apt:
    deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb

- name: execute 'apt-get update' to get zabbix repository package list
  apt:
    update_cache: yes

- name: install zabbix agent 2 package
  apt: name={{ packages }} state=present autoremove=yes
  vars:
    packages:
      - zabbix-agent2

- name: change /etc/zabbix/zabbix_agent2.conf
  copy: src=zabbix_agent2.conf dest=/etc/zabbix/zabbix_agent2.conf owner=root group=root mode=0644 backup=yes
  notify: restart zabbix-agent2