---
# tasks file for docker

- name: install packages
  apt: name={{ packages }} state=present autoremove=yes
  vars:
    packages:
      - chrony

- name: add apt key for docker packages
  apt_key: url='https://download.docker.com/linux/ubuntu/gpg' state=present

- name: add apt repository for docker
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable' filename='docker' state=present update_cache=yes

- name: install docker packages
  apt: name={{ packages }} state=present autoremove=yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: add vagrant user to docker group
  user: name=vagrant groups=docker append=yes

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
