---
# tasks file for common

- name: use apt-cacher for fast package updates
  copy: src=01proxy dest=/etc/apt/apt.conf.d/01proxy owner=root group=root mode=0644

##- name: add buster-backports repository
##  apt_repository: repo="deb http://ftp.debian.org/debian buster-backports main" state=present

##- name: update apt cache and install package reboot-notifier using default release buster-backport
##  apt: name=reboot-notifier state=latest default_release=buster-backports update_cache=yes cache_valid_time=3600

- name: set timezone to America/Sao_Paulo
  timezone: name=America/Sao_Paulo

- name: generate pt_BR.UTF-8 locales
  locale_gen: name=pt_BR.UTF-8 state=present
  notify: update locales

- name: flushing handler update locales
  meta: flush_handlers

- name: upgrade all system packages
  apt: update_cache=yes cache_valid_time=3600 upgrade=dist

- name: install packages
  apt: name={{ packages }} state=present autoremove=yes
  vars:
    packages:
      - chrony
      - libpam-systemd
      - vim
      - reboot-notifier

- name: get stat from /var/run/reboot-required file
  stat: path=/var/run/reboot-required
  register: reboot
 
- name: set default system editor
  alternatives: name=editor path=/usr/bin/vim.basic

- name: change /etc/vim/vimrc file
  copy: src=vimrc dest=/etc/vim/vimrc owner=root group=root mode=0644 backup=yes

- name: change /etc/bash.bashrc file
  copy: src=bash.bashrc dest=/etc/bash.bashrc owner=root group=root mode=0644 backup=yes

- name: change .bashrc file for user root
  copy: src=.bashrc.root dest=/root/.bashrc owner=root group=root mode=0644 backup=yes

- name: change .bashrc file for user vagrant
  copy: src=.bashrc.vagrant dest=/home/vagrant/.bashrc owner=vagrant group=vagrant mode=0644 backup=yes

- block:

  - name: restart box
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true

  - name: waiting for box to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=60
    become: false

  when: reboot.stat.exists

