---
# This playbook deploys the whole application stack in this site.

##- name: install python 3 if not installed
##  hosts: all
##  gather_facts: False
##  become: True

##  tasks:
##  - name: install python 3
##    raw: test -e /usr/bin/python3 || (apt update -y && apt install python3 -y)

- name: apply common configuration to all nodes
  hosts: all
  become: true

  roles:
  - common
  - swapfile
