---
# tasks file for kubectl

- name: add apt key for kubectl
  apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present

- name: add apt repository for kubectl
  apt_repository: repo='deb https://apt.kubernetes.io/ kubernetes-xenial main' filename='kubernetes' state=present update_cache=yes

- name: install packages
  apt: name={{ packages }} state=present
  vars:
    packages:
      - kubectl