---
# tasks file for mssql-server

- name: add apt key for mssql-server packages
  apt_key: url='https://packages.microsoft.com/keys/microsoft.asc' state=present

- name: add apt repository for mssql-server
  apt_repository: repo='deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal main' filename='mssql-server-2019.list' state=present update_cache=yes

- name: add apt repository for mssql-server tools
  apt_repository: repo='deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/ubuntu/20.04/prod focal main' filename='msprod.list' state=present update_cache=yes

- name: install mssql-server and tools packages
  apt: name={{ packages }} state=present autoremove=yes
  vars:
    packages:
      - mssql-server
      # - mssql-tools
      # - unixodbc-dev

