---
# tasks file for jenkins-slaves

- name: install packages
  apt: name={{ packages }} state=present autoremove=yes
  vars:
    packages:
      - openjdk-11-jdk-headless
      - chrony

- name: add group jenkins
  group: name=jenkins gid=121

- name: add user jenkins
  user: name=jenkins comment='Jenkins' createhome=yes group=jenkins uid=113 home=/var/lib/jenkins shell=/bin/bash state=present

- name: set authorized_key jenkins user
  authorized_key: user=jenkins key='{{ item }}' state=present
  with_file:
    - files/authorized_keys.jenkins

- name: set /var/lib/jenkins/.ssh/id_rsa
  copy: src=id_rsa.jenkins dest=/var/lib/jenkins/.ssh/id_rsa owner=jenkins group=jenkins mode=0600 backup=yes

- name: set /var/lib/jenkins/.ssh/config
  copy: src=config.ssh dest=/var/lib/jenkins/.ssh/config owner=jenkins group=jenkins mode=0600 backup=yes

- name: add jenkins user to docker group
  user: name=jenkins groups=docker append=yes
