---
# tasks file for jenkins-slaves

- name: insert/update IP address block in /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.56.161    jenkins01.vagrant.local  jenkins01
      192.168.56.162    jenkins02.vagrant.local  jenkins02
      192.168.56.163    jenkins03.vagrant.local	 jenkins03

- name: install openjdk-8-jdk-headless package first
  apt: name={{ packages }} state=present autoremove=yes
  vars:
    packages:
      - openjdk-8-jdk-headless

# - name: install packages
#   apt: name={{ packages }} state=present autoremove=yes
#   vars:
#     packages:
#       - maven

- name: add group jenkins
  group: name=jenkins gid=121

- name: add user jenkins
  user: name=jenkins comment='Jenkins' createhome=yes group=jenkins uid=113 home=/var/lib/jenkins shell=/bin/bash state=present

- name: set authorized_key jenkins user
  authorized_key: user=jenkins key='{{ item }}' state=present
  with_file:
    - files/authorized_keys.jenkins

- name: set /var/lib/jenkins/.ssh/id_rsa
  copy: src=id_rsa.jenkins dest=/var/lib/jenkins/.ssh/id_rsa owner=jenkins group=jenkins mode=0600 backup=yes

- name: set /var/lib/jenkins/.ssh/config
  copy: src=config.ssh dest=/var/lib/jenkins/.ssh/config owner=jenkins group=jenkins mode=0600 backup=yes
