---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  become: true

  roles:
  - common
  - mysql

# - name: apply common configuration to mysql-masters
#  hosts: mysql-masters
#  become: true
#
#  roles:
#  - mysql-masters
#
# - name: apply common configuration to mysql-slaves
#  hosts: mysql-slaves
#  become: true
#
#  roles:
#  - mysql-slaves
