---
# tasks file for rabbitmq

- name: install packages
  apt: name="{{ packages }}" state=present autoremove=yes
  vars:
    packages:
    - rabbitmq-server

- name: ensure users exist
  rabbitmq_user:
    user={{ item }}
    password={{ item }}
    tags={{ rabbitmq_administrator_tag }}
    state=present
  with_items: "{{ rabbitmq_users }}"

- name: ensure users are removed
  rabbitmq_user:
    user={{ item }}
    state=absent
  with_items: "{{ rabbitmq_users_remove }}"

- name: enable plugin
  rabbitmq_plugin: names={{ rabbitmq_plugins | join(',') }} state=enabled