apiVersion: v1
kind: Pod
metadata:
  labels:
    run: apod
  name: apod
spec:
  containers:
  - image: nginx
    name: nginx
  - image:  python:3.8
    name: python
    command:
      - "sleep"
      - "3600"
