---
# tasks file for jenkins

- name: add apt key for jenkins
  apt_key: url=https://pkg.jenkins.io/debian/jenkins.io.key state=present

- name: add apt repository for jenkins
  apt_repository: repo='deb http://pkg.jenkins.io/debian binary/' filename='jenkins' state=present update_cache=yes

- name: install openjdk-8-jdk package first
  apt: name=openjdk-8-jdk state=present

- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - jenkins
  - nginx
  - maven

- name: change /etc/nginx/sites-available/jenkins file
  copy: src=nginx_jenkins dest=/etc/nginx/sites-available/jenkins owner=root group=root mode=0644 backup=yes
  notify: restart nginx

- name: remove /etc/nginx/sites-enabled/default symbolic link
  file: path=/etc/nginx/sites-enabled/default state=absent follow=no
  notify: restart nginx

- name: create /etc/nginx/sites-enabled/jenkins symbolic link
  file: path=/etc/nginx/sites-enabled/jenkins src=/etc/nginx/sites-available/jenkins state=link
  notify: restart nginx
