---
# handlers file for common

- name: restart machine
  reboot:

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=60
  become: false
