---
# tasks file for awx

# - name: execute nodejs install script
#   command: /bin/bash -c "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -"

- name: add apt repository for ansible
  apt_repository: repo=ppa:ansible/ansible update_cache=yes

- name: install ansible package
  apt: name=ansible state=present

- name: install packages
  apt: name={{ packages }} state=present autoremove=yes
  vars:
    packages:
      - ansible
      - python-docker
      - nodejs
      - npm

- name: install npm package
  apt: name=npm state=present

- name: use npm to update itself
  npm: name=npm global=yes

- name: clone aws from github
  git: repo=https://github.com/ansible/awx.git dest=/opt/git/awx

- name: execute ansible to install awx
  command: ansible-playbook -i inventory install.yml
  args:
      chdir: /opt/git/awx/installer
