---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  become: true

  roles:
  - common
  - mongodb

# - name: apply configuration to mongodb_masters
#   hosts: mongodb_masters
#   become: true

#   roles:
#   - mongodb_masters

# - name: apply configuration to mongodb_slaves
#   hosts: mongodb_slaves
#   become: true

#   roles:
#   - mongodb_slaves
