---
# This playbook deploys the whole application stack in this site.

- name: install python-minimal (python 2) if not installed
  hosts: all
  gather_facts: False
  become: True

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt update -y && apt install python-minimal -y)

- name: apply common configuration to all nodes
  hosts: all
  become: True

  roles:
  - common
  - docker

- name: apply jenkins-masters configuration to jenkins masters nodes
  hosts: jenkins-masters
  become: True

  roles:
  - jenkins-masters

- name: apply jenkins-slaves configuration to jenkins slaves nodes
  hosts: jenkins-slaves
  become: True

  roles:
  - jenkins-slaves
